### ISSUE TITLE
Convert app to sveltekit and port over gallery functionality from webnative-app-template

### ISSUE THREAD

**Issue by avivash** [fission-codes/webnative-walletauth#4]
Since we're only able to use MetaMask for the foreseeable future, we don't really need RainbowKit anymore, which means we can 🪓 React from this app. I'm going to replace it with sveltekit and implement the gallery functionality from [webnative-app-template](https://github.com/fission-codes/webnative-app-template/), but using a DDD approach so it's easier for people to remove the gallery code if they don't need it. 

The newest version of [sveltekit](https://github.com/sveltejs/kit/discussions/5774) doesn't assume all files in the `routes` directory are actually routes(the file names need to have a `+` at the beginning to be interpreted as routes), so I can create a `gallery` directory in there and use it as the domain for this functionality 👍🏼

**Comment by icidasset** [comment]
https://github.com/webnative-examples/walletauth
